### ISSUE TITLE
Generation of file containing invalid records imported from user 

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#155]
Company admin is adding records of employees and menu items in bulk using CSV /Excel file. There might be any error in the csv/excel file which he/she is unable to find out. So a new downloadable file is needed to be generated which will contain all the invalid records along with their respective errors.

**Comment by meenakshikumari** [comment]
1. First of all the records which are already present in the employee/menu_item database will be counted first and stored in a variable. 
2. Now we will start a loop in which we are importing records from the csv/excel file and simultaneously keeping count of records present in the imported file.
3. If a particular record (or row) contains any error then we will append that row along with its error to a new csv/excel file. And if record is valid then it is saved to the database.
4. After completion of loop again records present in the employee/menu_item database will be counted  again and stored in another variable.
5. If the difference of  records present in  the employee/menu_item database is equal to number of records present in the imported file then a "Successfully Uploaded !!" flash message will be displayed , otherwise invalid records file download option will be displayed with a message "Some records are Invalid !!".

**Comment by gautamrege** [comment]
Oh no no no! 

+ Please read how menu items are saved and what validations the have on them.

My logic:
+ Try to insert the menu-item for that vendor.
+ In case of error, append error to CSV and continue to next record.
+ After best effort create is completed, ensure that the user can download the error-file. 

In your case, if you load all the menu items in a variable - consider the case that there are 5000 terminals with 500 menu items in it and we upload 1 duplicate! What a waste of memory and computation, right?

**Comment by meenakshikumari** [comment]
Sorry Sir for not specifying . 

- In my above comment i meant to say that we will take count for that particular vendor's menu items which was present before and after the importing the user csv/excel file 

- Then the difference of count will be matched with the number of records present in csv file. 

- And then accordingly we will proceed.

**Comment by gautamrege** [comment]
I don't see the need to take a count of menu items at all! When you get file of menu_items, process it! 
If error, add to error csv file. After all processing, if there are entries in the CSV file, that means some had errors! 

Why waste computation to find number of menu items before and after etc. Why add the complexity??

**Comment by meenakshikumari** [comment]
Ok sir. Should i start coding ?

**Comment by meenakshikumari** [comment]
A link for downloading invalid record file has been added to the employees and menu_items view page.
This file will show all the invalid records which was present in the imported csv from the user.
The user can access the latest invalid error file on clicking on that link.
All the required test cases has also been added.
