### ISSUE TITLE
Order Management

### ISSUE THREAD

**Issue by SakshiParakh** [joshsoftware/the_hunger_terminal#18]
- [ ] Order table with fields 
1. id
2. user_id
3. company_id
4. total_cost
5. date 

- [ ]  Associations between Order and other models
1. User has many orders
2. Company has many orders
3. Order has many vendors through order_details
4. Order has many menu_items through order_details

- [ ] Order_Details table fields
1. id 
2. order_id
3. menu_item_id
4. menu_item_name
5. vendor_id
6. vendor_name
7. quantity
8. rate

- [ ] test cases for order 
- [ ] Cruds for order (create order, delete order, update order)

**Comment by tejaswini-gambhire** [comment]
Some changes in above design
1. there will be no direct association between order and menu_items and also between order and vendor. 
2. there will be association like order has_many order_details
3. Fields in order table are user_id, company_id, date, total_cost
4. Fields in order_detail are 
   - order_id,
   - menu_item_name,
   - price,
   - quantity,
   - vendor_id

Approach:
1. Create order model and order_detail model
2. Some test case scenarios for order -
   - Order should have at least one menu_item otherwise order should not be created
   - Order can be updated before 10 AM only after that order cannot be updated
   - Order placed after 10 AM will get placed for next day i.e. date should be incremented by one
