### ISSUE TITLE
CompanyAdmin Dashboard

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/the_hunger_terminal#8]
- [x] Basic layout will be be similar to home page
- [x] Specific side bar components:
- Terminals 
- Employees
- Reports 
- Orders ( History of orders placed by the CompanyAdmin itself )  *page opens to this component*

*layout structure images to be attached*

**Comment by Shivamkumarsingh** [comment]
Thank you..

On 14 Feb 2017 2:39 p.m., "Sakshi Parakh" <notifications@github.com> wrote:

Assigned #8 <https://github.com/joshsoftware/the_hunger_terminal/issues/8>
to @Shivamkumarsingh <https://github.com/Shivamkumarsingh>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joshsoftware/the_hunger_terminal/issues/8#event-961010571>,
or mute the thread

**Comment by Shivamkumarsingh** [comment]
Today's Target

1. To complete sidebar component with some change in homepage .
2. To define routes for each action in sidebar.
3. Test Cases for routes to be define.

**Comment by Shivamkumarsingh** [comment]
@SakshiParakh There is no require controller and the corresponding action present  in the current stage of repo.so  how to define routes for the the link in sidebar?

**Comment by SakshiParakh** [comment]
@Shivamkumarsingh  dont make the controllers and routes for now then. But are you complete with the design of the sidebar??

**Comment by Shivamkumarsingh** [comment]
Done with  today's task i.e sidebar design.

**Comment by Shivamkumarsingh** [comment]
![welcome](https://cloud.githubusercontent.com/assets/16892315/23008977/480f65c8-f439-11e6-98aa-e0cc385eae1a.png).This is how the Company admin Dashboard looks like. 
@SakshiParakh What i have to do today ?
